<%@page import="at.wrk.coceso.entity.Unit"%>
<%@page import="java.util.Map"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>
<%--
/**
 * CoCeSo
 * Client HTML dashboard unit list view
 * Copyright (c) WRK\Coceso-Team
 *
 * Licensed under the GNU General Public License, version 3 (GPL-3.0)
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) 2014 WRK\Coceso-Team
 * @link https://sourceforge.net/projects/coceso/
 * @license GPL-3.0 ( http://opensource.org/licenses/GPL-3.0 )
 */
--%>

<c:url var="get_unit" value="?iid=${incident.id}&amp;uid="/>

<div class="dashboard-list">
  <p>
    <span class="key"><spring:message code="label.incident.type"/></span>
    <span <c:if test="${incident.blue}">class="blue"</c:if>>
      <c:choose>
        <c:when test="${incident.type == 'Task'}">
          <c:choose>
            <c:when test="${incident.blue}"><spring:message code="label.incident.type.task.blue"/></c:when>
            <c:otherwise><spring:message code="label.incident.type.task"/></c:otherwise>
          </c:choose>
        </c:when>
        <c:otherwise>
          <spring:message code="label.incident.type.${fn:toLowerCase(incident.type)}"/>
        </c:otherwise>
      </c:choose>
    </span>
  </p>

  <c:if test="${incident.type == 'Task' || incident.type == 'Transport'}">
    <p>
      <span class="key"><spring:message code="label.incident.bo"/></span>
      <span>
        <c:choose>
          <c:when test="${not empty incident.bo}"><c:out value="${incident.bo}"/></c:when>
          <c:otherwise><spring:message code="label.incident.nobo"/></c:otherwise>
        </c:choose>
      </span>
    </p>
  </c:if>

  <p>
    <span class="key"><spring:message code="label.incident.ao"/></span>
    <span>
      <c:choose>
        <c:when test="${not empty incident.ao}"><c:out value="${incident.ao}"/></c:when>
        <c:otherwise><spring:message code="label.incident.noao"/></c:otherwise>
      </c:choose>
    </span>
  </p>

  <c:if test="${not empty incident.info}">
    <p>
      <span class="key"><spring:message code="label.incident.info"/></span>
      <span><c:out value="${incident.info}"/></span>
    </p>
  </c:if>

  <c:if test="${not empty incident.caller}">
    <p>
      <span class="key"><spring:message code="label.incident.caller"/></span>
      <span><c:out value="${incident.caller}"/></span>
    </p>
  </c:if>

  <c:if test="${not empty incident.casusNr}">
    <p>
      <span class="key"><spring:message code="label.incident.casus"/></span>
      <span><c:out value="${incident.casusNr}"/></span>
    </p>
  </c:if>

  <p>
    <span class="key"><spring:message code="label.incident.state"/></span>
    <span><spring:message code="label.incident.state.${fn:toLowerCase(incident.state)}"/></span>
  </p>

  <c:forEach items="${units}" var="unit">
  <p>
    <span class="key"><c:out value="${unit.key.call}"/></span>
    <span><spring:message code="label.task.state.${fn:toLowerCase(unit.value)}"/></span>
  </p>
  </c:forEach>
  <!-- /ko -->
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Time</th>
      <th>User</th>
      <th>Text</th>
      <th>Unit</th>
      <th>State</th>
    </tr>
  </thead>
  <tbody>
    <c:forEach items="${logs}" var="log">
      <tr>
        <td><fmt:formatDate type="both" dateStyle="short" timeStyle="medium" value="${log.timestamp}"/></td>
        <td><c:out value="${log.user.username}"/></td>
        <td>
          <c:choose>
            <c:when test="${log.autoGenerated}"><spring:message code="descr.${log.type}"/></c:when>
            <c:otherwise><c:out value="${log.text}"/></c:otherwise>
          </c:choose>
        </td>
        <td>
          <a href="${get_unit}${log.unit.id}" data-toggle="popover" data-content="<c:out value="${log.json}"/>" data-trigger="hover"><c:out value="${log.unit.call}"/></a>
        </td>
        <td>
          <c:out value="${log.state}"/>
        </td>
        <td><c:out value="${log.json}"/></td>
      </tr>
    </c:forEach>
  </tbody>
</table>