<%@page import="at.wrk.coceso.entity.Unit"%>
<%@page import="java.util.Map"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%--
/**
 * CoCeSo
 * Client HTML dashboard unit list view
 * Copyright (c) WRK\Coceso-Team
 *
 * Licensed under the GNU General Public License, version 3 (GPL-3.0)
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) 2014 WRK\Coceso-Team
 * @link https://sourceforge.net/projects/coceso/
 * @license GPL-3.0 ( http://opensource.org/licenses/GPL-3.0 )
 */
--%>

<c:url var="get_inc" value="/dashboard?uid=${unit.id}&amp;iid="/>

<div class="alert alert-success">
  <strong><c:out value="${unit.call}"/>: </strong> <c:out value="${unit.info}"/><!-- TODO -->
</div>
<div class="page-header">
  <h3>
    Assigned Incidents:
  </h3>
</div>
<c:forEach var="incs" items="${unit.incidents}">
  <div class="alert alert-info">
    ID: <a href="${get_inc}${incs.key}" class="btn btn-primary">${incs.key}</a> : <c:out value="${incs.value}"/>
  </div>
</c:forEach>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Time</th>
      <th>User</th>
      <th>Text</th>
      <th>Incident</th>
      <th>State</th>
    </tr>
  </thead>
  <tbody>
    <c:forEach items="${logs}" var="log">
      <tr>
        <td><fmt:formatDate type="both" dateStyle="short" timeStyle="medium" value="${log.timestamp}"/></td>
        <td><c:out value="${log.user.username}"/></td>
        <td>
          <c:choose>
            <c:when test="${log.autoGenerated}"><spring:message code="descr.${log.type}" text="${log.text}"/></c:when>
            <c:otherwise><c:out value="${log.text}"/></c:otherwise>
          </c:choose>
        </td>
        <td>
          <a href="${get_inc}${log.incident.id}" data-toggle="popover" data-content="<c:out value="${log.json}"/>" data-trigger="hover"><c:out value="${log.incident.id}"/></a>
        </td>
        <td>
          <c:out value="${log.state}"/>
        </td>
        <td>
          <c:set var="changes" value="${log.changes}"/>
          <c:if test="${not empty changes}">
            <ul>
                <c:forEach items="${changes.data}" var="change" varStatus="key">
                  <li>
                    <spring:message code="label.${changes.type}.${change.key}" text="${change.key}"/>:
                    <c:out value="${change.value.oldValue}"/>
                    <span class="glyphicon glyphicon-arrow-right"></span>
                    <c:out value="${change.value.newValue}"/>
                  </li>
              </c:forEach>
            </ul>
          </c:if>
        </td>
      </tr>
    </c:forEach>
  </tbody>
</table>