package at.wrk.coceso.entity.enums;

public enum LogEntryType {

  CONCERN_CREATE, CONCERN_UPDATE, CONCERN_REMOVE, CONCERN_CLOSE, CONCERN_REOPEN,
  INCIDENT_CREATE, INCIDENT_UPDATE, INCIDENT_DELETE, INCIDENT_AUTO_STATE, INCIDENT_AUTO_DONE,
  UNIT_CREATE, UNIT_CREATE_REMOVED, UNIT_UPDATE, UNIT_ASSIGN, UNIT_DETACH, UNIT_AUTO_DETACH, UNIT_AUTOSET_POSITION,
  TASKSTATE_CHANGED,
  PATIENT_CREATE, PATIENT_UPDATE, PATIENT_ASSIGN,
  CUSTOM;
}
