package at.wrk.coceso.service;


import at.wrk.coceso.dao.LogDao;
import at.wrk.coceso.entities.*;
import at.wrk.coceso.utils.Logger;
import org.codehaus.jackson.map.ObjectMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.io.IOException;

@Service
public class LogService {
    @Autowired
    LogDao logDao;

    public void log(Person user, String text, int activeCase, Unit unit, Incident incident, boolean autoGenerated) {
        if(user == null) {
            Logger.error("LogService called without 'user'!");
            return;
        }
        LogEntry logEntry = new LogEntry();

        logEntry.user = user;
        logEntry.text = text;
        logEntry.unit = unit;
        logEntry.incident = incident;
        logEntry.autoGenerated = autoGenerated;

        logEntry.aCase = new Case();
        logEntry.aCase.id = activeCase;
        logEntry.state = incident != null && incident.units != null && unit != null ?
                incident.units.get(unit) : null;

        ObjectMapper mapper = new ObjectMapper();

        try {
            logEntry.json = mapper.writeValueAsString(new Object[] { unit, incident });
        } catch (IOException e) {
            e.printStackTrace();
        }

        logDao.add(logEntry);

    }
}
