package at.wrk.coceso.service;


import at.wrk.coceso.dao.LogDao;
import at.wrk.coceso.entity.*;
import at.wrk.coceso.utils.Logger;
import org.codehaus.jackson.map.ObjectMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.io.IOException;

@Service
public class LogService {
    @Autowired
    LogDao logDao;

    public void logFull(Operator user, String text, int activeCase, Unit unit, Incident incident, boolean autoGenerated) {
        if(user == null) {
            Logger.error("LogService called without 'user'!");
            return;
        }
        LogEntry logEntry = new LogEntry();

        logEntry.setUser(user);
        logEntry.setText(text);
        logEntry.setUnit(unit);
        logEntry.setIncident(incident);
        logEntry.setAutoGenerated(autoGenerated);

        logEntry.setConcern(new Concern());
        logEntry.getConcern().setId(activeCase);
        logEntry.setState(incident != null && incident.getUnits() != null && unit != null ?
                incident.getUnits().get(unit.getId()) : null);

        ObjectMapper mapper = new ObjectMapper();

        try {
            logEntry.setJson(mapper.writeValueAsString(new Object[] { unit, incident }));
        } catch (IOException e) {
            e.printStackTrace();
        }

        logDao.add(logEntry);

    }

    public void logWithIDs(int user_id, String text, int activeCase, int unit_id, int incident_id, boolean auto) {
        if(user_id < 1)
            return;
        logDao.add(activeCase, unit_id, incident_id, auto, user_id, text);
    }

    public void logByUser(Operator user, String text, int activeCase) {
        logFull(user, text, activeCase, null, null, false);
    }
}
