package at.wrk.coceso.entity;

import at.wrk.coceso.entity.enums.LogEntryType;
import at.wrk.coceso.entity.enums.TaskState;

import java.sql.Timestamp;

public class LogEntry {

    private int id;

    private Concern concern;

    private Timestamp timestamp;

    private Unit unit;

    private Incident incident;

    private TaskState state;

    private LogEntryType type;

    private boolean autoGenerated;

    private Operator user;

    private String text;

    private String json;

    // GETTER
    public Timestamp getTimestamp() {
        return timestamp;
    }

    public Unit getUnit() {
        return unit;
    }

    public Incident getIncident() {
        return incident;
    }

    public TaskState getState() {
        return state;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public Operator getUser() {
        return user;
    }

    public String getText() {
        return text;
    }

    public String getJson() {
        return json;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Concern getConcern() {
        return concern;
    }

    public void setConcern(Concern concern) {
        this.concern = concern;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    public void setUnit(Unit unit) {
        this.unit = unit;
    }

    public void setIncident(Incident incident) {
        this.incident = incident;
    }

    public void setState(TaskState state) {
        this.state = state;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public void setUser(Operator user) {
        this.user = user;
    }

    public void setText(String text) {
        this.text = text;
    }

    public void setJson(String json) {
        this.json = json;
    }

    public LogEntryType getType() {
        return type;
    }

    public void setType(LogEntryType type) {
        this.type = type;
    }
}
