START TRANSACTION;
DROP TABLE IF EXISTS selcall;
DROP TABLE IF EXISTS point;
DROP TABLE IF EXISTS concern;
DROP TABLE IF EXISTS unit;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS operator;
DROP TABLE IF EXISTS operator_role;
DROP TABLE IF EXISTS crew;
DROP TABLE IF EXISTS incident;
DROP TABLE IF EXISTS log;
DROP TABLE IF EXISTS task;
DROP TABLE IF EXISTS patient;
DROP TABLE IF EXISTS container;
DROP TABLE IF EXISTS unit_in_container;


DROP SEQUENCE IF EXISTS unit_id_seq;
DROP SEQUENCE IF EXISTS person_id_seq;
DROP SEQUENCE IF EXISTS log_id_seq;
DROP SEQUENCE IF EXISTS incident_id_seq;
DROP SEQUENCE IF EXISTS point_id_seq;
DROP SEQUENCE IF EXISTS concern_id_seq;
DROP SEQUENCE IF EXISTS role_id_seq;
DROP SEQUENCE IF EXISTS container_id_seq;
COMMIT;

