START TRANSACTION;
DROP TABLE IF EXISTS selcall CASCADE;
DROP TABLE IF EXISTS point CASCADE;
DROP TABLE IF EXISTS concern CASCADE;
DROP TABLE IF EXISTS unit CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS operator CASCADE;
DROP TABLE IF EXISTS operator_role CASCADE;
DROP TABLE IF EXISTS crew CASCADE;
DROP TABLE IF EXISTS incident CASCADE;
DROP TABLE IF EXISTS log CASCADE;
DROP TABLE IF EXISTS task CASCADE;
DROP TABLE IF EXISTS patient CASCADE;
DROP TABLE IF EXISTS container CASCADE;
DROP TABLE IF EXISTS unit_in_container CASCADE;


DROP SEQUENCE IF EXISTS unit_id_seq CASCADE;
DROP SEQUENCE IF EXISTS person_id_seq CASCADE;
DROP SEQUENCE IF EXISTS log_id_seq CASCADE;
DROP SEQUENCE IF EXISTS incident_id_seq CASCADE;
DROP SEQUENCE IF EXISTS point_id_seq CASCADE;
DROP SEQUENCE IF EXISTS concern_id_seq CASCADE;
DROP SEQUENCE IF EXISTS role_id_seq CASCADE;
DROP SEQUENCE IF EXISTS container_id_seq CASCADE;
DROP SEQUENCE IF EXISTS hibernate_sequence CASCADE;
COMMIT;
