package at.wrk.coceso.entities;

import at.wrk.coceso.entities.incidents.Incident;

import java.sql.Timestamp;

public class LogEntry {

    private int id;

    private Case aCase;

    private Timestamp timestamp;

    private Unit unit;

    private Incident incident;

    private TaskState state;

    private boolean autoGenerated;

    private Person user;

    private String text;

    private String json;

}
