package at.wrk.coceso.entities;

import java.sql.Timestamp;

public class LogEntry {

    private int id;

    private Case aCase;

    private Timestamp timestamp;

    private Unit unit;

    private Incident incident;

    private TaskState state;

    private boolean autoGenerated;

    private String signOfUser;

    private String text;

    private String json;

}
