INSERT INTO VORFALL
(VSTART, VENDE, VTYP, VTEXT, VSTATUS )
VALUES ('2013-08-09 15:00:00', '2013-08-09 20:00:00', 'EINSATZ', 'Verkehrsunfall', 'ABGESCHLOSSEN')

INSERT INTO PUBLIC.EINHEIT
(ENAME, ETYP, ESTATUS )
VALUES ('4.0414', 'SEW', 'EB');

INSERT INTO PUBLIC.EINHEIT
(ENAME, ETYP, ESTATUS )
VALUES ('005', 'Trupp', 'EB');

INSERT INTO PUBLIC.EINHEIT
(ENAME, ETYP, ESTATUS )
VALUES ('89', 'KTW', 'EB');

INSERT INTO PUBLIC.EINHEIT
(ENAME, ETYP, ESTATUS )
VALUES ('RD05', 'RTW', 'EB');