package at.wrk.coceso.dao;

import at.wrk.coceso.dao.mapper.LogMapper;
import at.wrk.coceso.entity.LogEntry;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.stereotype.Repository;

import javax.sql.DataSource;
import java.sql.Timestamp;
import java.util.List;

@Repository
public class LogDao extends CocesoDao<LogEntry> {

  @Autowired
  private LogMapper logMapper;

  @Autowired
  public LogDao(DataSource dataSource) {
    super(dataSource);
  }

  private static final String getPrefix = "SELECT l.*, u.call, "
          + "p.sur_name, p.given_name, p.dnr, p.contact, o.username, "
          + "i.blue, i.type AS itype, bo.info AS bo, ao.info AS ao "
          + "FROM log l "
          + "LEFT JOIN operator o ON o.id = l.operator_fk  "
          + "LEFT JOIN person p   ON p.id = l.operator_fk  "
          + "LEFT JOIN unit u     ON u.id = l.unit_fk "
          + "LEFT JOIN incident i ON i.id = l.incident_fk "
          + "LEFT JOIN point bo   ON bo.id = i.bo_point_fk "
          + "LEFT JOIN point ao   ON ao.id = i.ao_point_fk ";

  private static final String sortSuffix = " ORDER BY l.timestamp DESC, l.id DESC";

  @Override
  public LogEntry getById(int id) {
    if (id <= 0) {
      return null;
    }

    String q = getPrefix + "WHERE l.id = ?";

    try {
      return jdbc.queryForObject(q, new Object[]{id}, logMapper);
    } catch (DataAccessException e) {
      return null;
    }
  }

  public List<LogEntry> getByUnitId(int id) {
    if (id <= 0) {
      return null;
    }

    String q = getPrefix + "WHERE l.unit_fk = ?" + sortSuffix;

    return jdbc.query(q, new Object[]{id}, logMapper);
  }

  public List<LogEntry> getLimitedByUnitId(int id, int limit) {
    if (id <= 0) {
      return null;
    }

    String q = getPrefix + "WHERE l.unit_fk = ?" + sortSuffix + "  LIMIT ?";

    return jdbc.query(q, new Object[]{id, limit}, logMapper);
  }

  public List<LogEntry> getByIncidentId(int id) {
    if (id <= 0) {
      return null;
    }

    String q = getPrefix + "WHERE l.incident_fk = ?" + sortSuffix;

    return jdbc.query(q, new Object[]{id}, logMapper);
  }

  public List<LogEntry> getByIncidentAndUnit(int incident_id, int unit_id) {
    if (unit_id <= 0 || incident_id <= 0) {
      return null;
    }

    String q = getPrefix + "WHERE l.incident_fk = ? AND l.unit_fk = ?" + sortSuffix;

    return jdbc.query(q, new Object[]{incident_id, unit_id}, logMapper);
  }

  @Override
  public List<LogEntry> getAll(int id) {
    if (id <= 0) {
      return null;
    }

    String q = getPrefix + "WHERE l.concern_fk = ?" + sortSuffix;

    return jdbc.query(q, new Object[]{id}, logMapper);
  }

  @Override
  public boolean update(LogEntry logEntry) {
    throw new UnsupportedOperationException();
  }

  protected boolean updateForRemoval(int unitId) {
    String q = "UPDATE log SET unit_fk = NULL, text = 'Unit created - REMOVED', type = 'UNIT_CREATE_REMOVED' WHERE type = 'UNIT_CREATE' AND unit_fk = ?";
    jdbc.update(q, unitId);
    return true;
  }

  @Override
  public int add(LogEntry l) {
    String q = "INSERT INTO log (timestamp, concern_fk, unit_fk, incident_fk, taskstate, autogenerated, "
            + "operator_fk, text, json, type) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    jdbc.update(q,
            new Timestamp(System.currentTimeMillis()),
            l.getConcern().getId(),
            l.getUnit() == null ? null : l.getUnit().getId(),
            l.getIncident() == null ? null : l.getIncident().getId(),
            l.getState() == null ? null : l.getState().name(),
            l.isAutoGenerated(),
            l.getUser().getId(),
            l.getText(),
            l.getJson(),
            l.getType() == null ? null : l.getType().name());

    return 0;
  }

  @Override
  public boolean remove(LogEntry logEntry) {
    throw new UnsupportedOperationException();
  }

  public List<LogEntry> getLast(int case_id, int count) {
    String q = getPrefix + "WHERE l.concern_fk = ? " + sortSuffix + "  LIMIT ?";

    return jdbc.query(q, new Object[]{case_id, count}, logMapper);
  }

  public List<LogEntry> getCustom(int concernId) {
    if (concernId <= 0) {
      return null;
    }

    String q = getPrefix + "WHERE l.type = 'CUSTOM' AND l.concern_fk = ?" + sortSuffix;

    return jdbc.query(q, new Object[]{concernId}, logMapper);
  }
}
