START TRANSACTION;

ALTER TABLE task
    ADD COLUMN lastStateChangeAt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT '2020-01-01 12:00:00';
ALTER TABLE task
    ALTER COLUMN lastStateChangeAt DROP DEFAULT;

-- fix missing timezone on timestamps.
ALTER TABLE incident
    ALTER COLUMN created TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN arrival TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN stateChange TYPE TIMESTAMP WITH TIME ZONE,
    ALTER COLUMN ended TYPE TIMESTAMP WITH TIME ZONE;

COMMIT;
